[package]
name = "computer-specs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.23.5"
timer = "0.2.0"
chrono = "0.4.19"
